import Experience from '@/Three/Experience';
import { Canvas } from '@react-three/fiber';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>penguins-ice-breaker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Canvas
        shadows
        camera={{
          fov: 45,
          near: 0.1,
          far: 200,
          position: [2.5, 4, 6],
        }}
      >
        <Experience />
      </Canvas>
    </>
  );
}
